2021-11-15 00:13:14.369 | WARNING  | autodidaqt_common.remote.schema:get_definition:208 - Improperly handled type ObjectType()
2021-11-15 00:13:14.393 | WARNING  | autodidaqt_common.remote.schema:from_type:261 - Assuming naive implementation of Array and Object types.
2021-11-15 00:13:14.395 | INFO     | autodidaqt.core:start:768 - Application in startup.
2021-11-15 00:13:14.396 | INFO     | autodidaqt.core:start:769 - CommandLineConfig(headless=False, remote_config=None)
2021-11-15 00:13:14.397 | INFO     | autodidaqt.core:start:770 - {'version': '0.0.0', 'debug': True, 'logging': True, 'logging_directory': 'out\\logs', 'log_format': '{time}-{user}-{session}', 'save_format': 'pickle', 'data_directory': 'out\\data', 'data_format': '{user}\\{date}-{name}-{session}-{run}', 'maintain_state': True, 'state_directory': 'out\\state', 'instruments': {'simulate_instruments': False}, 'use_profiles': False, 'profiles': {}}
2021-11-15 00:13:14.399 | INFO     | autodidaqt.core:start:775 - Configuring Qt application and styles
2021-11-15 00:13:15.301 | INFO     | autodidaqt.core:configure_event_loop:746 - Configuring async runtime
2021-11-15 00:13:15.303 | INFO     | autodidaqt.core:configure_event_loop:753 - Using asyncio for async support.
2021-11-15 00:13:15.306 | INFO     | autodidaqt.core:configure_event_loop:763 - Setting custom exception handler on async loop
2021-11-15 00:13:23.286 | INFO     | autodidaqt.core:launch_panel:130 - Opening panel _instrument_manager
2021-11-15 00:13:23.306 | INFO     | autodidaqt.panels.instrument_manager:launch_panel:21 - Instrument Manager: Opening panel analyzer
2021-11-15 00:13:24.058 | INFO     | autodidaqt.panels.instrument_manager:launch_panel:21 - Instrument Manager: Opening panel phony
2021-11-15 00:13:24.346 | INFO     | autodidaqt.core:launch_panel:130 - Opening panel experiment
2021-11-15 00:13:24.401 | INFO     | autodidaqt.core:master:548 - Started async loop.
2021-11-15 00:13:24.402 | INFO     | autodidaqt.core:master:567 - Running actor .prepare
2021-11-15 00:13:24.404 | INFO     | autodidaqt.experiment.fsm:transition_to:42 - {'match': <ExperimentTransitions.Initialize: 'initialize'>, 'to': <ExperimentStates.Idle: 'IDLE'>}, initialize
2021-11-15 00:13:24.405 | INFO     | autodidaqt.core:master:584 - Installing Qt event processing on the standard event loop
2021-11-15 00:13:24.406 | INFO     | autodidaqt.core:load_state:690 - Loading application state.
2021-11-15 00:13:24.694 | INFO     | autodidaqt.core:load_state:694 - Found candidate application state: C:\Users\admin.TOF-PEEM\documents\peem-daq\out\state\2021-11-12T17-08-31-448082.state.pickle... loading.
2021-11-15 00:13:24.736 | INFO     | autodidaqt.core:load_state:719 - Finished loading application state.
2021-11-15 00:13:24.740 | INFO     | autodidaqt.core:master:589 - Main task is dropping into event loop
2021-11-15 00:13:24.747 | INFO     | daq.ether_daq.instrument:write_communications_file:86 - EtherDAQDriver opened communications file to EtherDAQ: C:\Users\admin.TOF-PEEM\tmp\frame.txt
2021-11-15 00:13:33.810 | WARNING  | daq.ether_daq.instrument:read_frame:125 - No communication with EtherDAQ: File not found after 9.0 seconds.
2021-11-15 00:13:33.818 | INFO     | daq.ether_daq.instrument:write_communications_file:86 - EtherDAQDriver opened communications file to EtherDAQ: C:\Users\admin.TOF-PEEM\tmp\frame.txt
2021-11-15 00:13:42.908 | WARNING  | daq.ether_daq.instrument:read_frame:125 - No communication with EtherDAQ: File not found after 9.0 seconds.
2021-11-15 00:13:42.912 | INFO     | daq.ether_daq.instrument:write_communications_file:86 - EtherDAQDriver opened communications file to EtherDAQ: C:\Users\admin.TOF-PEEM\tmp\frame.txt
2021-11-15 00:13:51.992 | WARNING  | daq.ether_daq.instrument:read_frame:125 - No communication with EtherDAQ: File not found after 9.0 seconds.
2021-11-15 00:13:52.000 | INFO     | daq.ether_daq.instrument:write_communications_file:86 - EtherDAQDriver opened communications file to EtherDAQ: C:\Users\admin.TOF-PEEM\tmp\frame.txt
2021-11-15 00:14:01.020 | WARNING  | daq.ether_daq.instrument:read_frame:125 - No communication with EtherDAQ: File not found after 9.0 seconds.
2021-11-15 00:14:01.028 | INFO     | daq.ether_daq.instrument:write_communications_file:86 - EtherDAQDriver opened communications file to EtherDAQ: C:\Users\admin.TOF-PEEM\tmp\frame.txt
2021-11-15 00:14:06.871 | INFO     | autodidaqt.experiment.fsm:transition_to:42 - {'match': <ExperimentTransitions.Start: 'start'>, 'to': <ExperimentStates.Running: 'RUNNING'>}, start
2021-11-15 00:14:06.886 | INFO     | daq.ether_daq.instrument:write_communications_file:86 - EtherDAQDriver opened communications file to EtherDAQ: C:\Users\admin.TOF-PEEM\tmp\frame.txt
2021-11-15 00:14:10.036 | WARNING  | daq.ether_daq.instrument:read_frame:125 - No communication with EtherDAQ: File not found after 9.0 seconds.
2021-11-15 00:14:10.041 | INFO     | daq.ether_daq.instrument:write_communications_file:86 - EtherDAQDriver opened communications file to EtherDAQ: C:\Users\admin.TOF-PEEM\tmp\frame.txt
2021-11-15 00:14:15.950 | WARNING  | daq.ether_daq.instrument:read_frame:125 - No communication with EtherDAQ: File not found after 9.0 seconds.
2021-11-15 00:14:15.958 | INFO     | daq.ether_daq.instrument:write_communications_file:86 - EtherDAQDriver opened communications file to EtherDAQ: C:\Users\admin.TOF-PEEM\tmp\frame.txt
2021-11-15 00:14:19.053 | WARNING  | daq.ether_daq.instrument:read_frame:125 - No communication with EtherDAQ: File not found after 9.0 seconds.
2021-11-15 00:14:19.056 | INFO     | daq.ether_daq.instrument:write_communications_file:86 - EtherDAQDriver opened communications file to EtherDAQ: C:\Users\admin.TOF-PEEM\tmp\frame.txt
2021-11-15 00:14:24.991 | WARNING  | daq.ether_daq.instrument:read_frame:125 - No communication with EtherDAQ: File not found after 9.0 seconds.
2021-11-15 00:14:24.994 | INFO     | daq.ether_daq.instrument:write_communications_file:86 - EtherDAQDriver opened communications file to EtherDAQ: C:\Users\admin.TOF-PEEM\tmp\frame.txt
2021-11-15 00:14:28.116 | WARNING  | daq.ether_daq.instrument:read_frame:125 - No communication with EtherDAQ: File not found after 9.0 seconds.
2021-11-15 00:14:28.124 | INFO     | daq.ether_daq.instrument:write_communications_file:86 - EtherDAQDriver opened communications file to EtherDAQ: C:\Users\admin.TOF-PEEM\tmp\frame.txt
2021-11-15 00:14:28.727 | WARNING  | autodidaqt.core:shutdown:417 - Shutting down due to exception.
2021-11-15 00:14:28.731 | INFO     | autodidaqt.core:shutdown:419 - Shutting down process pool.
2021-11-15 00:14:28.736 | INFO     | autodidaqt.core:shutdown:421 - Finished shutting down process pool.
2021-11-15 00:14:28.740 | INFO     | autodidaqt.core:shutdown:423 - Saving...
2021-11-15 00:14:28.743 | INFO     | autodidaqt.core:save_state:722 - Saving application state.
2021-11-15 00:14:28.757 | INFO     | autodidaqt.core:save_state:730 - Finished saving application state.
2021-11-15 00:14:28.761 | INFO     | autodidaqt.core:shutdown:427 - Application is still reading messages. Stopping...
2021-11-15 00:14:28.764 | INFO     | autodidaqt.core:shutdown:431 - Sending graceful shutdown requests.
2021-11-15 00:14:28.766 | INFO     | autodidaqt.core:shutdown:441 - Waiting graceful shutdown requests.
2021-11-15 00:14:28.809 | INFO     | autodidaqt.instrument.managed_instrument:shutdown:213 - Shutting down ['stages', 0]
2021-11-15 00:14:28.810 | INFO     | autodidaqt.instrument.managed_instrument:shutdown:215 - Finished shutting down ['stages', 0]
2021-11-15 00:14:28.812 | INFO     | autodidaqt.instrument.managed_instrument:shutdown:213 - Shutting down ['stages', 1]
2021-11-15 00:14:28.813 | INFO     | autodidaqt.instrument.managed_instrument:shutdown:215 - Finished shutting down ['stages', 1]
2021-11-15 00:14:28.815 | INFO     | autodidaqt.instrument.managed_instrument:shutdown:213 - Shutting down ['stages', 2]
2021-11-15 00:14:28.816 | INFO     | autodidaqt.instrument.managed_instrument:shutdown:215 - Finished shutting down ['stages', 2]
2021-11-15 00:14:31.764 | ERROR    | autodidaqt.core:shutdown:449 - Not all actors have shut down after 3.0 seconds. Bad actors are ['experiment', 'analyzer']
2021-11-15 00:14:31.769 | WARNING  | autodidaqt.core:shutdown:455 - Cancelling tasks... 4 tasks remaining expected 1.
2021-11-15 00:14:31.773 | INFO     | autodidaqt.core:shutdown:470 - Waiting on finished tasks...
2021-11-15 00:14:31.778 | INFO     | autodidaqt.core:shutdown:481 - Stopping loop
2021-11-15 00:14:31.783 | INFO     | autodidaqt.core:start:794 - Closed autodidaqt successfully.
2021-11-15 00:14:31.797 | ERROR    | autodidaqt.core:handle_exception:382 - Caught Unhandled: Task was destroyed but it is pending!
