2021-11-01 16:59:08.403 | WARNING  | autodidaqt_common.remote.schema:get_definition:208 - Improperly handled type ObjectType()
2021-11-01 16:59:08.407 | WARNING  | autodidaqt_common.remote.schema:from_type:261 - Assuming naive implementation of Array and Object types.
2021-11-01 16:59:08.412 | INFO     | autodidaqt.core:start:768 - Application in startup.
2021-11-01 16:59:08.415 | INFO     | autodidaqt.core:start:769 - CommandLineConfig(headless=False, remote_config=None)
2021-11-01 16:59:08.419 | INFO     | autodidaqt.core:start:770 - {'version': '0.0.0', 'debug': True, 'logging': True, 'logging_directory': 'out\\logs', 'log_format': '{time}-{user}-{session}', 'save_format': 'pickle', 'data_directory': 'out\\data', 'data_format': '{user}\\{date}-{name}-{session}-{run}', 'maintain_state': True, 'state_directory': 'out\\state', 'instruments': {'simulate_instruments': False}, 'use_profiles': False, 'profiles': {}}
2021-11-01 16:59:08.423 | INFO     | autodidaqt.core:start:775 - Configuring Qt application and styles
2021-11-01 16:59:08.521 | INFO     | autodidaqt.core:configure_event_loop:746 - Configuring async runtime
2021-11-01 16:59:08.522 | INFO     | autodidaqt.core:configure_event_loop:753 - Using asyncio for async support.
2021-11-01 16:59:08.524 | INFO     | autodidaqt.core:configure_event_loop:763 - Setting custom exception handler on async loop
2021-11-01 16:59:08.978 | INFO     | autodidaqt.core:launch_panel:130 - Opening panel _instrument_manager
2021-11-01 16:59:08.983 | INFO     | autodidaqt.panels.instrument_manager:launch_panel:21 - Instrument Manager: Opening panel analyzer
2021-11-01 16:59:09.526 | INFO     | autodidaqt.panels.instrument_manager:launch_panel:21 - Instrument Manager: Opening panel phony
2021-11-01 16:59:09.695 | INFO     | autodidaqt.core:launch_panel:130 - Opening panel experiment
2021-11-01 16:59:09.764 | INFO     | autodidaqt.core:master:548 - Started async loop.
2021-11-01 16:59:09.765 | INFO     | autodidaqt.core:master:567 - Running actor .prepare
2021-11-01 16:59:09.767 | INFO     | autodidaqt.experiment.fsm:transition_to:42 - {'match': <ExperimentTransitions.Initialize: 'initialize'>, 'to': <ExperimentStates.Idle: 'IDLE'>}, initialize
2021-11-01 16:59:09.769 | INFO     | autodidaqt.core:master:584 - Installing Qt event processing on the standard event loop
2021-11-01 16:59:09.770 | INFO     | autodidaqt.core:load_state:690 - Loading application state.
2021-11-01 16:59:09.782 | INFO     | autodidaqt.core:load_state:694 - Found candidate application state: C:\Users\admin.TOF-PEEM\documents\peem-daq\out\state\2021-11-01T16-57-47-191179.state.pickle... loading.
2021-11-01 16:59:09.838 | INFO     | autodidaqt.core:load_state:719 - Finished loading application state.
2021-11-01 16:59:09.842 | INFO     | autodidaqt.core:master:589 - Main task is dropping into event loop
2021-11-01 16:59:09.849 | INFO     | daq.ether_daq.instrument:write_communications_file:86 - EtherDAQDriver opened communications file to EtherDAQ: C:\Users\admin.TOF-PEEM\tmp\frame.txt
2021-11-01 16:59:18.886 | WARNING  | daq.ether_daq.instrument:read_frame:125 - No communication with EtherDAQ: File not found after 9.0 seconds.
2021-11-01 16:59:18.897 | INFO     | daq.ether_daq.instrument:write_communications_file:86 - EtherDAQDriver opened communications file to EtherDAQ: C:\Users\admin.TOF-PEEM\tmp\frame.txt
2021-11-01 16:59:27.936 | WARNING  | daq.ether_daq.instrument:read_frame:125 - No communication with EtherDAQ: File not found after 9.0 seconds.
2021-11-01 16:59:27.943 | INFO     | daq.ether_daq.instrument:write_communications_file:86 - EtherDAQDriver opened communications file to EtherDAQ: C:\Users\admin.TOF-PEEM\tmp\frame.txt
2021-11-01 16:59:29.645 | WARNING  | autodidaqt.core:shutdown:417 - Shutting down due to exception.
2021-11-01 16:59:29.649 | INFO     | autodidaqt.core:shutdown:419 - Shutting down process pool.
2021-11-01 16:59:29.654 | INFO     | autodidaqt.core:shutdown:421 - Finished shutting down process pool.
2021-11-01 16:59:29.657 | INFO     | autodidaqt.core:shutdown:423 - Saving...
2021-11-01 16:59:29.661 | INFO     | autodidaqt.core:save_state:722 - Saving application state.
2021-11-01 16:59:29.673 | INFO     | autodidaqt.core:save_state:730 - Finished saving application state.
2021-11-01 16:59:29.677 | INFO     | autodidaqt.core:shutdown:427 - Application is still reading messages. Stopping...
2021-11-01 16:59:29.681 | INFO     | autodidaqt.core:shutdown:431 - Sending graceful shutdown requests.
2021-11-01 16:59:29.685 | INFO     | autodidaqt.core:shutdown:441 - Waiting graceful shutdown requests.
2021-11-01 16:59:29.706 | INFO     | autodidaqt.instrument.managed_instrument:shutdown:213 - Shutting down ['stages', 0]
2021-11-01 16:59:29.710 | INFO     | autodidaqt.instrument.managed_instrument:shutdown:215 - Finished shutting down ['stages', 0]
2021-11-01 16:59:29.714 | INFO     | autodidaqt.instrument.managed_instrument:shutdown:213 - Shutting down ['stages', 1]
2021-11-01 16:59:29.718 | INFO     | autodidaqt.instrument.managed_instrument:shutdown:215 - Finished shutting down ['stages', 1]
2021-11-01 16:59:29.722 | INFO     | autodidaqt.instrument.managed_instrument:shutdown:213 - Shutting down ['stages', 2]
2021-11-01 16:59:29.725 | INFO     | autodidaqt.instrument.managed_instrument:shutdown:215 - Finished shutting down ['stages', 2]
2021-11-01 16:59:32.700 | ERROR    | autodidaqt.core:shutdown:449 - Not all actors have shut down after 3.0 seconds. Bad actors are ['analyzer']
2021-11-01 16:59:32.705 | WARNING  | autodidaqt.core:shutdown:455 - Cancelling tasks... 2 tasks remaining expected 1.
2021-11-01 16:59:32.709 | INFO     | autodidaqt.core:shutdown:470 - Waiting on finished tasks...
2021-11-01 16:59:32.713 | INFO     | autodidaqt.core:shutdown:481 - Stopping loop
2021-11-01 16:59:32.717 | INFO     | autodidaqt.core:start:794 - Closed autodidaqt successfully.
